export const POKEMON_SEASONS = [
  { id: 's01', name: 'Indigo League',                          episodes: 82  },
  { id: 's02', name: 'Adventures in the Orange Islands',       episodes: 36  },
  { id: 's03', name: 'The Johto Journeys',                     episodes: 41  },
  { id: 's04', name: 'Johto League Champions',                 episodes: 52  },
  { id: 's05', name: 'Master Quest',                           episodes: 65  },
  { id: 's06', name: 'Advanced',                               episodes: 40  },
  { id: 's07', name: 'Advanced Challenge',                     episodes: 52  },
  { id: 's08', name: 'Advanced Battle',                        episodes: 54  },
  { id: 's09', name: 'Battle Frontier',                        episodes: 47  },
  { id: 's10', name: 'Diamond and Pearl',                      episodes: 51  },
  { id: 's11', name: 'DP: Battle Dimension',                   episodes: 52  },
  { id: 's12', name: 'DP: Galactic Battles',                   episodes: 53  },
  { id: 's13', name: 'DP: Sinnoh League Victors',              episodes: 34  },
  { id: 's14', name: 'Black & White',                          episodes: 48  },
  { id: 's15', name: 'BW: Rival Destinies',                    episodes: 49  },
  { id: 's16', name: 'BW: Adventures in Unova',                episodes: 45  },
  { id: 's17', name: 'XY',                                     episodes: 48  },
  { id: 's18', name: 'XY: Kalos Quest',                        episodes: 45  },
  { id: 's19', name: 'XYZ',                                    episodes: 47  },
  { id: 's20', name: 'Sun & Moon',                             episodes: 43  },
  { id: 's21', name: 'Sun & Moon: Ultra Adventures',           episodes: 49  },
  { id: 's22', name: 'Sun & Moon: Ultra Legends',              episodes: 54  },
  { id: 's23', name: 'Journeys',                               episodes: 48  },
  { id: 's24', name: 'Master Journeys',                        episodes: 45  },
  { id: 's25', name: 'Ultimate Journeys',                      episodes: 49  },
  { id: 's26', name: 'Horizons',                               episodes: 23  },
  { id: 's27', name: 'Horizons: The Series',                   episodes: 60  },
]